# Generated by Django 2.0.5 on 2018-10-26 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultoras', '0003_auto_20180829_1453'),
        ('produtos', '0004_auto_20181025_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('consultora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultora', to='consultoras.Consultora')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='produtos.Produto')),
            ],
        ),
    ]
