# Generated by Django 2.0.5 on 2018-08-16 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=200)),
                ('data_nascimento', models.DateTimeField(verbose_name='Data de nascimento')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
