# Generated by Django 2.0.5 on 2018-08-16 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultoras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultora',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
