# Generated by Django 2.0.5 on 2018-08-29 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultoras', '0002_auto_20180816_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultora',
            name='bairro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consultora',
            name='celular',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consultora',
            name='cidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consultora',
            name='desconto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consultora',
            name='endereco',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consultora',
            name='primeiro_nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consultora',
            name='telefone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consultora',
            name='ultimo_nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultora',
            name='nivel',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultora',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultora',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
