# Generated by Django 2.0.5 on 2018-11-24 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0004_auto_20181025_1603'),
        ('consultoras', '0003_auto_20180829_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_consultora', to='consultoras.Consultora')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_pedido', to='pedidos.Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_produto', to='produtos.Produto')),
            ],
        ),
    ]
